### ISSUE TITLE
Suggestion to rename the lesson to more accurately reflect video content

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/rails-video-review-flatiron-store-review#1]
This video covers the Flatiron Store lab, but it isn't really a 'review.'  The video starts with discussion of a student's solution that is already in-progress (e.g,. doesn't start with first code written to begin resolving the specs).  The video moves into troubleshooting that student's error messages related to her associations and authentication approach.  The troubleshooting can be a valuable resource, particularly for students that get an error similar to "undefined method 'val' for #<Arel:...>" (see ~ 18:41).  The existing title and readme text, though, implies that the video content will be a more comprehensive discussion of solving the lab.  Suggestion is for a more specific lesson title that accurately reflects the video's content, e.g., "Rails Video Review: Flatiron Store - Debugging Association, Authentication Errors"

**Comment by gj** [comment]
Updated @christinalcole — thanks again!
